{"Id": "66590207", "PostTypeId": "1", "CreationDate": "2021-03-11T20:38:00.590", "Score": "0", "ViewCount": "3110", "Body": "<p>This is a tricky question, because the Terraform plan fails, but the network was created. All this is very strange.</p>\n<p>After a all long day trying  to solve, I'm quit. Only for the GCP team knowledge I document the problem here. If anybody knows the answer, please enlightenment me.</p>\n<p>I'be working with Terrafom for more than 18 months and when I try something new is a nightmare find the solution. Now, this is the case. The plan executes wonderful with the GCP provider version 2.15, but in version 3 fails miserably in the cli with this error:</p>\n<p><strong>Error: Error waiting to create Network: Error waiting for Creating Network: error while retrieving operation: googleapi: Error 400: Invalid value for field 'project': 'projects/nvi-classdir-e954783d'. Must be a match of regex '(?:(?:[-a-z0-9]{1,63}.)*(?:a-z?):)?(?:[0-9]{1,19}|(?:a-z0-9?))', invalid</strong></p>\n<p>But in my GCP was created, AMAZING!!!</p>\n<p><a href=\"https://i.stack.imgur.com/wfsBw.png\" rel=\"nofollow noreferrer\">Network was created always</a></p>\n<p>The problem was all the execution plan fails after because this error. My solution was simple, get back to 2.15 GCP provider. If somebody knows what happened here, please tell me.</p>\n<p>My plan:</p>\n<pre><code>module &quot;project&quot; {\n  source          = &quot;../../modules/2021/gc-project&quot;\n  name            = &quot;nvi-${var.sufix}&quot;\n  region          = &quot;${var.region}&quot;\n  billing_account = &quot;${var.billing_account}&quot;\n  org_id          = &quot;${var.org_id}&quot;\n  # domain          = &quot;${var.domain}&quot;\n}\n\nmodule &quot;network&quot; {\n  source                = &quot;../../modules/2021/network&quot;\n  name                  = &quot;${module.project.name}&quot;\n  project_id            = &quot;${module.project.id}&quot;\n  region                = &quot;${var.region}&quot;\n  zones                 = &quot;${var.zones}&quot;\n  hosts_subnet_name     = &quot;${var.subnet_id}&quot;\n  hosts_subnet_ip_range = &quot;${var.hosts_subnet_ip_range}&quot;\n  net                   = &quot;${var.net_name}&quot;\n  db_ext_access         = false # Disable external access to database\n}\n</code></pre>\n<p>My network module:</p>\n<pre><code>resource &quot;google_compute_network&quot; &quot;network&quot; {\n  name                    = &quot;${var.net}-network&quot;\n  project                 = &quot;${var.project_id}&quot;\n  auto_create_subnetworks = false\n}\n</code></pre>\n<p>The execution plan:</p>\n<pre><code>An execution plan has been generated and is shown below.\nResource actions are indicated with the following symbols:\n  + create\n\nTerraform will perform the following actions:\n\n  module.network.google_compute_network.network will be created\n  + resource &quot;google_compute_network&quot; &quot;network&quot; {\n      + auto_create_subnetworks         = false\n      + delete_default_routes_on_create = false\n      + gateway_ipv4                    = (known after apply)\n      + id                              = (known after apply)\n      + mtu                             = (known after apply)\n      + name                            = &quot;voz-e-imagen-network&quot;\n      + project                         = &quot;projects/nvi-classdir-e954783d&quot;\n      + routing_mode                    = (known after apply)\n      + self_link                       = (known after apply)\n    }\n\nPlan: 1 to add, 0 to change, 0 to destroy.\n</code></pre>\n", "OwnerUserId": "11886029", "LastActivityDate": "2021-10-23T14:00:32.457", "Title": "Terraform GCP create network fails. Error 400", "Tags": "<networking><terraform-provider-gcp><infrastructure-as-code>", "AnswerCount": "1", "CommentCount": "1", "ContentLicense": "CC BY-SA 4.0", "comments": [{"Id": "132614394", "PostId": "66590207", "Score": "0", "Text": "In my case, project that I want to attach was host project. And it was not discoverable. After moving it to related organization, it worked fine!", "CreationDate": "2023-01-17T17:12:46.483", "UserId": "7044786", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}], "history": [{"Id": "242492751", "PostHistoryTypeId": "2", "PostId": "66590207", "RevisionGUID": "ca4cef3f-c077-49d4-b22c-3110b2ee5a5c", "CreationDate": "2021-03-11T20:38:00.590", "UserId": "11886029", "Text": "This is a tricky question, because the Terraform plan fails, but the network was created. All this is very strange.\r\n\r\nAfter a all long day trying  to solve, I'm quit. Only for the GCP team knowledge I document the problem here. If anybody knows the answer, please enlightenment me.\r\n\r\nI'be working with Terrafom for more than 18 months and when I try something new is a nightmare find the solution. Now, this is the case. The plan executes wonderful with the GCP provider version 2.15, but in version 3 fails miserably in the cli with this error:\r\n\r\n**Error: Error waiting to create Network: Error waiting for Creating Network: error while retrieving operation: googleapi: Error 400: Invalid value for field 'project': 'projects/nvi-classdir-e954783d'. Must be a match of regex '(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z0-9](?:[-a-z0-9]{0,61}[a-z0-9])?))', invalid**\r\n\r\nBut in my GCP was created, AMAZING!!!\r\n\r\n[Network was created always][1]\r\n\r\nThe problem was all the execution plan fails after because this error. My solution was simple, get back to 2.15 GCP provider. If somebody knows what happened here, please tell me.\r\n\r\nMy plan:\r\n\r\n    module \"project\" {\r\n      source          = \"../../modules/2021/gc-project\"\r\n      name            = \"nvi-${var.sufix}\"\r\n      region          = \"${var.region}\"\r\n      billing_account = \"${var.billing_account}\"\r\n      org_id          = \"${var.org_id}\"\r\n      # domain          = \"${var.domain}\"\r\n    }\r\n    \r\n    module \"network\" {\r\n      source                = \"../../modules/2021/network\"\r\n      name                  = \"${module.project.name}\"\r\n      project_id            = \"${module.project.id}\"\r\n      region                = \"${var.region}\"\r\n      zones                 = \"${var.zones}\"\r\n      hosts_subnet_name     = \"${var.subnet_id}\"\r\n      hosts_subnet_ip_range = \"${var.hosts_subnet_ip_range}\"\r\n      net                   = \"${var.net_name}\"\r\n      db_ext_access         = false # Disable external access to database\r\n    }\r\n\r\n\r\nMy network module:\r\n\r\n    resource \"google_compute_network\" \"network\" {\r\n      name                    = \"${var.net}-network\"\r\n      project                 = \"${var.project_id}\"\r\n      auto_create_subnetworks = false\r\n    }\r\n\r\nThe execution plan:\r\n\r\n    An execution plan has been generated and is shown below.\r\n    Resource actions are indicated with the following symbols:\r\n      + create\r\n    \r\n    Terraform will perform the following actions:\r\n    \r\n      module.network.google_compute_network.network will be created\r\n      + resource \"google_compute_network\" \"network\" {\r\n          + auto_create_subnetworks         = false\r\n          + delete_default_routes_on_create = false\r\n          + gateway_ipv4                    = (known after apply)\r\n          + id                              = (known after apply)\r\n          + mtu                             = (known after apply)\r\n          + name                            = \"voz-e-imagen-network\"\r\n          + project                         = \"projects/nvi-classdir-e954783d\"\r\n          + routing_mode                    = (known after apply)\r\n          + self_link                       = (known after apply)\r\n        }\r\n    \r\n    Plan: 1 to add, 0 to change, 0 to destroy.\r\n\r\n  [1]: https://i.stack.imgur.com/wfsBw.png\r\n\r\n", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": [{"source": "Text", "text": "The plan executes wonderful with the GCP provider version 2.15, but in version 3 fails miserably in the cli with this error: **Error: Error waiting to create Network: Error waiting for Creating Network: error while retrieving operation: googleapi: Error 400: Invalid value for field 'project': 'projects/nvi-classdir-e954783d'. ", "keywords": ["provider"]}, {"source": "Text", "text": "My solution was simple, get back to 2.15 GCP provider. ", "keywords": ["provider"]}, {"source": "Text", "text": "My plan: module \"project\" { source = \"../../modules/2021/gc-project\" name = \"nvi-${var.sufix}\" region = \"${var.region}\" billing_account = \"${var.billing_account}\" org_id = \"${var.org_id}\" # domain = \"${var.domain}\" } module \"network\" { source = \"../../modules/2021/network\" name = \"${module.project.name}\" project_id = \"${module.project.id}\" region = \"${var.region}\" zones = \"${var.zones}\" hosts_subnet_name = \"${var.subnet_id}\" hosts_subnet_ip_range = \"${var.hosts_subnet_ip_range}\" net = \"${var.net_name}\" db_ext_access = false # Disable external access to database } My network module: resource \"google_compute_network\" \"network\" { name = \"${var.net}-network\" project = \"${var.project_id}\" auto_create_subnetworks = false } ", "keywords": ["bill", "domain"]}, {"source": "Text", "text": "Resource actions are indicated with the following symbols: + create Terraform will perform the following actions: module.network.google_compute_network.network will be created + resource \"google_compute_network\" \"network\" { + auto_create_subnetworks = false + delete_default_routes_on_create = false + gateway_ipv4 = (known after apply) + id = (known after apply) + mtu = (known after apply) + name = \"voz-e-imagen-network\" + project = \"projects/nvi-classdir-e954783d\" + routing_mode = (known after apply) + self_link = (known after apply) } Plan: 1 to add, 0 to change, 0 to destroy. [1]: https://i.stack.imgur.com/wfsBw.png", "keywords": ["change"]}]}, {"Id": "242492752", "PostHistoryTypeId": "1", "PostId": "66590207", "RevisionGUID": "ca4cef3f-c077-49d4-b22c-3110b2ee5a5c", "CreationDate": "2021-03-11T20:38:00.590", "UserId": "11886029", "Text": "Terraform GCP create network fails. Error 400", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}, {"Id": "242492753", "PostHistoryTypeId": "3", "PostId": "66590207", "RevisionGUID": "ca4cef3f-c077-49d4-b22c-3110b2ee5a5c", "CreationDate": "2021-03-11T20:38:00.590", "UserId": "11886029", "Text": "<networking><terraform-provider-gcp><infrastructure-as-code>", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}], "answers": [{"Id": "69682658", "PostTypeId": "2", "ParentId": "66590207", "CreationDate": "2021-10-22T20:18:23.497", "Score": "0", "Body": "<p>Problem seems to be that <code>project.id</code> returns <code>project/[PROJECT_ID]</code>, while the API only expects the ID without <code>project</code> in front. Source: <a href=\"https://cloud.google.com/compute/docs/reference/rest/v1/networks/insert\" rel=\"nofollow noreferrer\">https://cloud.google.com/compute/docs/reference/rest/v1/networks/insert</a></p>\n<p>Good news is the <code>google_project</code> resource and data in Terraform also returns the project number. So replace <code>project.id</code> for <code>project.number</code> and it should work.</p>\n", "OwnerUserId": "17223038", "LastEditorUserId": "8961316", "LastEditDate": "2021-10-23T14:00:32.457", "LastActivityDate": "2021-10-23T14:00:32.457", "CommentCount": "0", "ContentLicense": "CC BY-SA 4.0", "history": [{"Id": "256421240", "PostHistoryTypeId": "2", "PostId": "69682658", "RevisionGUID": "75770905-b9ee-409f-9417-49833d27782b", "CreationDate": "2021-10-22T20:18:23.497", "UserId": "17223038", "Text": "Problem seems to be that project.id returns \"project/[PROJECT_ID]\", while the API only expects the ID without \"project\" in front - https://cloud.google.com/compute/docs/reference/rest/v1/networks/insert\r\n\r\nGood news is the \"google_project\" resource and data in Terraform also returns the project number. So replace \"project.id\" for \"project.number\" and it should work.", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}, {"Id": "256464407", "PostHistoryTypeId": "5", "PostId": "69682658", "RevisionGUID": "b41d57e7-92e6-4714-ac77-d35fee441d92", "CreationDate": "2021-10-23T14:00:32.457", "UserId": "8961316", "Comment": "updated formatting", "Text": "Problem seems to be that `project.id` returns `project/[PROJECT_ID]`, while the API only expects the ID without `project` in front. Source: https://cloud.google.com/compute/docs/reference/rest/v1/networks/insert\r\n\r\nGood news is the `google_project` resource and data in Terraform also returns the project number. So replace `project.id` for `project.number` and it should work.", "ContentLicense": "CC BY-SA 4.0", "filtered-sentences": []}], "filtered-sentences": []}], "contains-topic": true, "filtered-sentences": [{"source": "Body", "text": "The plan executes wonderful with the GCP provider version 2.15, but in version 3 fails miserably in the cli with this error: Error: Error waiting to create Network: Error waiting for Creating Network: error while retrieving operation: googleapi: Error 400: Invalid value for field 'project': 'projects/nvi-classdir-e954783d'. ", "keywords": ["provider"]}, {"source": "Body", "text": "My solution was simple, get back to 2.15 GCP provider. ", "keywords": ["provider"]}]}